@rootUrl = http://localhost:8000

#API List

### Check server status

GET {{rootUrl}}

### insert new USER

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"b",
    "lName":"b",
    "email":"b@b.com",
    "password":"Aa123#"
}

### post to activate  USER

POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
"sessionId":"688ab12c520d4cbc52205eb4",
 "t":"ad7406d1-d7ae-4161-b498-70b1bb516cbf"
}