@rootUrl = http://localhost:8000

#API List

### Check server status

GET {{rootUrl}}

### insert new USER

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"rrrrrr",
    "lName":"rrrrrr",
    "email":"r@t.com",
    "password":"Aa123#"
}

### post to activate  USER

POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
"sessionId":"688bf7461f719842927ca28b",
 "t":"ea137a9c-1d94-41a0-ad06-289691d6404a"
}

### login user

POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email":"z@z.com",
    "password":"Aa123#"
}